import type { Metadata } from "next";
import Link from "next/link";
import Logo from "./components/images/logo";
import "./globals.css";

export const metadata: Metadata = {
  title: "npm | Sign In",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='body'>
          <div className='box'>
            <Link href='/' aria-label='Npm' className='logo'>
              <Logo />
            </Link>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
